### ISSUE TITLE
to-do-list

### ISSUE THREAD

**Issue by KhineZinThaw7** [KhineZinThaw7/scm-bulletin-board-ROR#5]
To Do List (SCM Bulletin Board ROR) (18/1/2022)
----------------------------------------------
- [x] Post's Image Upload
- [x] Login and Register Validation
- [x] Search value must be contain when Search and make filter Search
- [x] Make user's role and permission
- [x] Make catgeories and relationship with posts
- [x] Post active or inactive
- [x] Post Detail Page
- [x] Review code
- [x] CSV Import
- [x] Chart and Graph
- [x] Rails Mailer
- [x] Localization
